import type { Metadata } from "next";
import Footer from "./components/layout/Footer";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import Navbar from "@/app/components/layout/Navbar";
import SmoothScroll from "@/app/components/layout/SmoothScroll";
import PreloaderGate, {
  preloaderSkipScript,
} from "@/app/components/layout/PreloaderGate";

const neueMontreal = localFont({
  src: [
    {
      path: "../public/fonts/NeueMontreal-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/NeueMontreal-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/NeueMontreal-Medium.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-neue-montreal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vyrl Communications",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.avif",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html
        lang="en"
        className={`${neueMontreal.variable} h-full antialiased`}
      >
        <body  className="min-h-full">
          {/* beforeInteractive scripts are always injected into <head>
              by Next.js regardless of where they're placed — this runs
              before hydration/paint and stamps a class on <html> if
              this session already saw the preloader, so globals.css can
              hide it instantly with zero flash instead of waiting for a
              client effect to decide that after the page has painted. */}
          <Script
            id="preloader-skip-check"
            strategy="beforeInteractive"
            dangerouslySetInnerHTML={{ __html: preloaderSkipScript }}
          />
          <PreloaderGate />
          <SmoothScroll />
          {/* <Header /> */}
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ViewTransitions>
  );
}
