import type { Metadata } from "next";
import GlobalFooter from "./components/layout/GlobalFooter";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";
import "./styles/heromodel-section.css";
import { ViewTransitions } from "next-view-transitions";
import Navbar from "@/app/components/layout/Navbar";
import SmoothScroll from "@/app/components/layout/SmoothScroll";
import PreloaderGate, {
  preloaderSkipScript,
} from "@/app/components/layout/PreloaderGate";
import Chatbot from "@/app/components/layout/Chatbot";
import FluidBackground from "@/app/components/layout/FluidBackgroundLoader";

const laygrotesk = localFont({
  src: [
    {
      path: "../public/fonts2/laygrotesk-trial-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts2/laygrotesk-trial-medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts2/laygrotesk-trial-semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts2/laygrotesk-trial-bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts2/laygrotesk-trial-black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-laygrotesk",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vyrl Communications",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.avif",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" className={`${laygrotesk.variable} h-full antialiased`}>
        <body className="min-h-full">
        
          {/* <Script
            id="preloader-skip-check"
            strategy="beforeInteractive"
            dangerouslySetInnerHTML={{ __html: preloaderSkipScript }}
          /> */}
          <PreloaderGate />
          {/* <FluidBackground /> */}
          <SmoothScroll />
          {/* <Header /> */}
          <Navbar />
          {children}
        
          <GlobalFooter />
          <Chatbot />
        </body>
      </html>
    </ViewTransitions>
  );
}
